/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school0;

import Main.Main;
import classes.DBConnexion;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.runtime.Debug.id;
import static org.omg.CORBA.ARG_IN.value;
import static school0.PRINCIPAL.tbel_model;
import school0.pkg1.login;
//import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;

/**
 *
 * @author MOHAMED
 */
public class add_model extends javax.swing.JFrame {

    /**
     * Creates new form add_model
     */
    public add_model() {
        initComponents();
         updateCompo();
    }
ResultSet result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_model = new javax.swing.JTextField();
        pai_model = new javax.swing.JTextField();
        nivo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        add_model = new javax.swing.JButton();
        idm = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("اسم المادة");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("المستوي");

        nom_model.setBorder(null);
        nom_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_modelActionPerformed(evt);
            }
        });

        pai_model.setBorder(null);
        pai_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pai_modelActionPerformed(evt);
            }
        });
        pai_model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pai_modelKeyTyped(evt);
            }
        });

        nivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        nivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("سعر المادة");

        add_model.setText("اضافة");
        add_model.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_modelMouseClicked(evt);
            }
        });
        add_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_modelActionPerformed(evt);
            }
        });

        idm.setBackground(new java.awt.Color(153, 204, 255));
        idm.setForeground(new java.awt.Color(153, 204, 255));
        idm.setBorder(null);
        idm.setCaretColor(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nivo, 0, 177, Short.MAX_VALUE)
                            .addComponent(nom_model, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pai_model, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(idm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(add_model, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(idm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_model, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pai_model, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(add_model, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("اضافة مادة");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nom_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_modelActionPerformed

    private void pai_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pai_modelActionPerformed
      

    }//GEN-LAST:event_pai_modelActionPerformed

    private void nivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivoActionPerformed
        
        
    }//GEN-LAST:event_nivoActionPerformed
    PreparedStatement perpar;
    private void add_modelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_modelMouseClicked
     
        /*    String id=nom_model.getText().toString();
            String nem=   pai_model.getText().toString();
            String pren=   nivo.getItemAt(WIDTH).toString();
            String Cle=cle.getText().toString();
            int nums = Integer.parseInt(Cle);
           int num = Integer.parseInt(pren);
           double nume = Double.parseDouble(nem);
            String sql="INSERT INTO `module`(`Num_Module`, `Nom_Module`, `prix`, `Num_niveau`) VALUES (?,?,?,?)";
            try {

                perpar=  login.cnx.prepareStatement(sql);
 perpar.setString(1, id);
                perpar.setString(2, id);

                perpar.setDouble(3,nume);

                perpar.setInt(4, num);

             

                perpar.execute();
                
                nom_model.setText("");
               pai_model.setText("");
               

            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");

            }*/
           
    }//GEN-LAST:event_add_modelMouseClicked

    
    private void updateCompo(){
    
    String sql="SELECT * FROM `niveau` ";

   
        try {
            perpar=  login.cnx.prepareStatement(sql);
            ResultSet rs=  perpar.executeQuery();
          
            while(rs.next()){
            nivo.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }
  
    private void add_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_modelActionPerformed
if(verf()==true){
    
       int lastRowIndex;
         
        String id=nom_model.getText().toString();
            String nem=   pai_model.getText().toString();
            String  niveau =   nivo.getSelectedItem().toString();
            
           double nume = Double.parseDouble(nem);
          
        
                

          
      String sql = "INSERT INTO `module`(`Nom_Module`, `prix`, `Num_niveau`) "
           + "SELECT ?, ?, `Num_niveau` FROM `niveau` WHERE `Nom_niveau`=?";
try {
    perpar = login.cnx.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    perpar.setString(1, id);
    perpar.setDouble(2, nume);
    perpar.setString(3, niveau);
    perpar.executeUpdate();

    
    ResultSet generatedKeys = perpar.getGeneratedKeys();
    if (generatedKeys.next()) {
        int primaryKeyValue = generatedKeys.getInt(1);
        

      
        DefaultTableModel model = (DefaultTableModel) tbel_model.getModel();
        lastRowIndex = model.getRowCount() - 1;
        model.setValueAt(primaryKeyValue, lastRowIndex, 0);
        idm.setText(lastRowIndex +"");
    }
} catch ( Exception e) {
    // Handle the exception
}

 Main.AddRowtoJTable(new Object[]{
         nivo.getSelectedItem(),   pai_model.getText(), nom_model.getText(), });

            
            tbel_model.repaint();
            }else{
     JOptionPane.showMessageDialog(null, "ادخل البيانات من فضلك");
}
 this.dispose();
    }//GEN-LAST:event_add_modelActionPerformed

    private void pai_modelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pai_modelKeyTyped
   char c=evt.getKeyChar();
   if(!Character.isDigit(c)){
   evt.consume();
   }
    }//GEN-LAST:event_pai_modelKeyTyped

   

    
    
    private boolean verf(){
     boolean a=true;
  if(nom_model.getText().equals("")||pai_model.getText().equals("")|| nivo.getSelectedItem().equals(""))
  {
  a=false;
  }
     return a;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new add_model().setVisible(true);
                add_model ad=new add_model();
                ad.setVisible(true);
                ad.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_model;
    private javax.swing.JTextField idm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> nivo;
    private javax.swing.JTextField nom_model;
    private javax.swing.JTextField pai_model;
    // End of variables declaration//GEN-END:variables
}
