/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school0;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static Main.Main.tabel_étudiants;
import static Main.Main.table_reservation;
import school0.pkg1.login;

/**
 *
 * @author MOHAMED
 */
public class modife_reservation extends javax.swing.JFrame {

    /**
     * Creates new form modife_reservation
     */
    public modife_reservation() {
        initComponents();
         updateCompo();
    }
    PreparedStatement prepared;
    ResultSet result;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nivo = new javax.swing.JComboBox<>();
        ComboBox_module = new javax.swing.JComboBox<>();
        ComboBox_enseignant = new javax.swing.JComboBox<>();
        ComboBox_groupe = new javax.swing.JComboBox<>();
        btn_modife_reservation = new javax.swing.JButton();
        nom_etuden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("المرحلة :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("المادة :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("الاستاذ :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("الفوج :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("الطالب :");

        nivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        nivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivoActionPerformed(evt);
            }
        });

        ComboBox_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_moduleActionPerformed(evt);
            }
        });

        ComboBox_enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_enseignantActionPerformed(evt);
            }
        });

        btn_modife_reservation.setText("حفظ");
        btn_modife_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modife_reservationActionPerformed(evt);
            }
        });

        nom_etuden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nom_etuden.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nom_etuden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBox_module, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBox_enseignant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBox_groupe, 0, 105, Short.MAX_VALUE)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_modife_reservation)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nom_etuden, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBox_module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBox_enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btn_modife_reservation)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivoActionPerformed
        ComboBox_module.removeAllItems();
        nivo.addActionListener(nivo) ;
        String selectedvalue=(String) nivo.getSelectedItem();
        String sql="SELECT * FROM `module` WHERE `Num_niveau` IN(SELECT `Num_niveau` FROM `niveau` WHERE `Nom_niveau`=?)";

        try {
            prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1, selectedvalue);
            ResultSet rs=  prepared.executeQuery();
            while(rs.next()){
                ComboBox_module.addItem(rs.getString(2));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_nivoActionPerformed

    private void ComboBox_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_moduleActionPerformed
        ComboBox_enseignant.removeAllItems();
        ComboBox_module.addActionListener(ComboBox_module) ;
        String selectedvalue=(String) ComboBox_module.getSelectedItem();
        String sql="SELECT  * FROM `enseignant` WHERE `Num_Enseignant`IN(SELECT `Num_Enseignant` FROM `groupe` WHERE `groupe`.`Num_Module` IN(SELECT `Num_Module` FROM `module` WHERE `Nom_Module`=?))";
        try {
            prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1, selectedvalue);
            ResultSet rs=  prepared.executeQuery();
            while(rs.next()){
                ComboBox_enseignant.addItem(rs.getString(2));
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_ComboBox_moduleActionPerformed

    private void ComboBox_enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_enseignantActionPerformed

        ComboBox_groupe.removeAllItems();
        ComboBox_enseignant.addActionListener(ComboBox_enseignant) ;
        String selectedvalue=(String) ComboBox_enseignant.getSelectedItem();
        String module= (String)ComboBox_module.getSelectedItem();
        String sql="SELECT DISTINCT `Num_Groupe`,`Nom_Groupe` FROM `groupe` G,`enseignant` WHERE G.`Num_Enseignant`"
        +"IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) AND G.`Num_Module`"
        +" IN(SELECT `Num_Module` FROM `module` WHERE `Nom_Module`=? )";
        //  String sql= " SELECT DISTINCT `Nom_Groupe` FROM `groupe` G,`enseignant` E,`module` M WHERE G.`Num_Enseignant`=E.`Num_Enseignant` AND G.`Num_Module`=M.`Num_Module` AND G.`Num_Enseignant`IN(SELECT E.`Num_Enseignant` FROM `enseignant` WHERE E.`Nom_Enseignant`=?) AND G.`Num_Module` IN(SELECT M.`Num_Module` FROM `module` M WHERE M.`Nom_Module`=?)";

        try {
            prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1, selectedvalue);
            prepared.setString(2, module);
            ResultSet rs=  prepared.executeQuery();
            while(rs.next()){
                ComboBox_groupe.addItem(rs.getString(2));
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_ComboBox_enseignantActionPerformed

    private void btn_modife_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modife_reservationActionPerformed
 int index=tabel_étudiants.getSelectedRow();
       String id_etudient= (String)tabel_étudiants.getModel().getValueAt(index, 9);
         int index1=table_reservation.getSelectedRow();
       String id_reservation= (String)table_reservation.getModel().getValueAt(index1, 4);
       String date = (String)table_reservation.getModel().getValueAt(index1, 3);
       String groupe= (String)ComboBox_groupe.getSelectedItem().toString();
           
                
      String sql=" UPDATE `reservation` SET `Date_Reservation`=?,`Num_Etudient`=?,`Num_Groupe`=(SELECT `Num_Groupe` FROM `groupe` WHERE `Nom_Groupe`=?) WHERE `Num_Reservation`=?";
            try {
                
             prepared  =  login.cnx.prepareStatement(sql);
                
               prepared.setString(1, date);
               prepared.setString(2,id_etudient);
               prepared.setString(3,groupe );
                prepared.setString(4,id_reservation );
                prepared.execute();

            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
   
            }
             this.dispose();
    }//GEN-LAST:event_btn_modife_reservationActionPerformed
 private void updateCompo(){
    
    String sql="SELECT * FROM `niveau` ";

   
        try {
            prepared=  login.cnx.prepareStatement(sql);
            ResultSet rs=  prepared.executeQuery();
          
            while(rs.next()){
            nivo.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modife_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modife_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modife_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modife_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modife_reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_enseignant;
    private javax.swing.JComboBox<String> ComboBox_groupe;
    private javax.swing.JComboBox<String> ComboBox_module;
    private javax.swing.JButton btn_modife_reservation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> nivo;
    public javax.swing.JLabel nom_etuden;
    // End of variables declaration//GEN-END:variables
}
