/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import school0.pkg1.login;

/**
 *
 * @author MZI System
 */
public class affectation_groupe_science1 extends javax.swing.JFrame {

   
    public affectation_groupe_science1() {
        initComponents();
         
         vendredi_Combobox();
         samdi_Combobox();
         dimanche_Combobox();
         lundi_Combobox();
         maredi_Combobox();
         marecredi_Combobox();
         jeudi_Combobox();

          ComboBox_vendredi.setEnabled(false);
          ComboBox_samedi.setEnabled(false);
          ComboBox_dimanche.setEnabled(false);
          ComboBox_lundi.setEnabled(false);
          ComboBox_maredi.setEnabled(false);
          ComboBox_marecredi.setEnabled(false);
          ComboBox_jeudi.setEnabled(false);
          
           module_combobox();
        enseignant_combobox();
        Salle_combobox();
    }
PreparedStatement prepared;
    ResultSet result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_groupe_science = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CheckBox_vendredi = new javax.swing.JCheckBox();
        ComboBox_vendredi = new javax.swing.JComboBox<>();
        CheckBox_samedi = new javax.swing.JCheckBox();
        ComboBox_samedi = new javax.swing.JComboBox<>();
        CheckBox_dimanche = new javax.swing.JCheckBox();
        ComboBox_dimanche = new javax.swing.JComboBox<>();
        CheckBox_lundi = new javax.swing.JCheckBox();
        ComboBox_lundi = new javax.swing.JComboBox<>();
        CheckBox_mardi = new javax.swing.JCheckBox();
        ComboBox_maredi = new javax.swing.JComboBox<>();
        CheckBox_mercredi = new javax.swing.JCheckBox();
        ComboBox_marecredi = new javax.swing.JComboBox<>();
        CheckBox_jeudi = new javax.swing.JCheckBox();
        ComboBox_jeudi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBox_module = new javax.swing.JComboBox<>();
        ComboBox_ensein = new javax.swing.JComboBox<>();
        ComboBox_Salle = new javax.swing.JComboBox<>();
        Txt_nomgroupe = new javax.swing.JTextField();
        Panel_M_P = new javax.swing.JPanel();
        Panel_vide = new javax.swing.JPanel();
        Panel_Massage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        Button_groupe_science.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Button_groupe_science.setText("حفظ");
        Button_groupe_science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_groupe_scienceActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)), "المواعيد", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        CheckBox_vendredi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_vendredi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_vendredi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_vendredi.setText("الجمعة   ");
        CheckBox_vendredi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckBox_vendredi.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        CheckBox_vendredi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox_vendrediMouseClicked(evt);
            }
        });
        CheckBox_vendredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_vendrediActionPerformed(evt);
            }
        });

        ComboBox_vendredi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_vendredi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_vendrediMouseClicked(evt);
            }
        });
        ComboBox_vendredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_vendrediActionPerformed(evt);
            }
        });

        CheckBox_samedi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_samedi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_samedi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_samedi.setText("السبت   ");
        CheckBox_samedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_samediActionPerformed(evt);
            }
        });

        ComboBox_samedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_samedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_samediMouseClicked(evt);
            }
        });
        ComboBox_samedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_samediActionPerformed(evt);
            }
        });

        CheckBox_dimanche.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_dimanche.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_dimanche.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_dimanche.setText("الاحد     ");
        CheckBox_dimanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_dimancheActionPerformed(evt);
            }
        });

        ComboBox_dimanche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_dimanche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_dimancheMouseClicked(evt);
            }
        });
        ComboBox_dimanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_dimancheActionPerformed(evt);
            }
        });

        CheckBox_lundi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_lundi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_lundi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_lundi.setText("الاثنين   ");
        CheckBox_lundi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_lundiActionPerformed(evt);
            }
        });

        ComboBox_lundi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_lundi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_lundiMouseClicked(evt);
            }
        });
        ComboBox_lundi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_lundiActionPerformed(evt);
            }
        });

        CheckBox_mardi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_mardi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_mardi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_mardi.setText("الثلاثاء   ");
        CheckBox_mardi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_mardiActionPerformed(evt);
            }
        });

        ComboBox_maredi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_maredi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_marediMouseClicked(evt);
            }
        });
        ComboBox_maredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_marediActionPerformed(evt);
            }
        });

        CheckBox_mercredi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_mercredi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_mercredi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_mercredi.setText("الاربعاء   ");
        CheckBox_mercredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_mercrediActionPerformed(evt);
            }
        });

        ComboBox_marecredi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_marecredi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_marecrediMouseClicked(evt);
            }
        });
        ComboBox_marecredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_marecrediActionPerformed(evt);
            }
        });

        CheckBox_jeudi.setBackground(new java.awt.Color(51, 102, 255));
        CheckBox_jeudi.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CheckBox_jeudi.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_jeudi.setText("الخميس");
        CheckBox_jeudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_jeudiActionPerformed(evt);
            }
        });

        ComboBox_jeudi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_jeudi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBox_jeudiMouseClicked(evt);
            }
        });
        ComboBox_jeudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_jeudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_jeudi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(CheckBox_jeudi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_marecredi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_mercredi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_maredi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_mardi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_dimanche, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_dimanche, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_vendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_vendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_samedi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_samedi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboBox_lundi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckBox_lundi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox_vendredi)
                    .addComponent(ComboBox_vendredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox_samedi)
                    .addComponent(ComboBox_samedi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_dimanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox_dimanche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_lundi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox_lundi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_maredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox_mardi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox_mercredi)
                    .addComponent(ComboBox_marecredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBox_jeudi)
                    .addComponent(ComboBox_jeudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("المادة :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الاستاذ :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("القاعة :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("الفوج :");

        ComboBox_module.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        ComboBox_ensein.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        ComboBox_Salle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        Panel_M_P.setBackground(new java.awt.Color(51, 102, 255));
        Panel_M_P.setLayout(new java.awt.CardLayout());

        Panel_vide.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout Panel_videLayout = new javax.swing.GroupLayout(Panel_vide);
        Panel_vide.setLayout(Panel_videLayout);
        Panel_videLayout.setHorizontalGroup(
            Panel_videLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        Panel_videLayout.setVerticalGroup(
            Panel_videLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        Panel_M_P.add(Panel_vide, "card2");

        Panel_Massage.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("يوجد عدم تناسق للاستاذ او للقاعة");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("عرض التفاصيل");

        javax.swing.GroupLayout Panel_MassageLayout = new javax.swing.GroupLayout(Panel_Massage);
        Panel_Massage.setLayout(Panel_MassageLayout);
        Panel_MassageLayout.setHorizontalGroup(
            Panel_MassageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_MassageLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_MassageLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_MassageLayout.setVerticalGroup(
            Panel_MassageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MassageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_M_P.add(Panel_Massage, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_groupe_science, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox_module, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_ensein, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_Salle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txt_nomgroupe))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Panel_M_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_groupe_science, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBox_module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBox_ensein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBox_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_nomgroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Panel_M_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox_lundiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_lundiActionPerformed
        
         if(CheckBox_lundi.isSelected()){
           ComboBox_lundi.setEnabled(true);
        }else{
          ComboBox_lundi.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_lundiActionPerformed

    private void CheckBox_mercrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_mercrediActionPerformed
         if(CheckBox_mercredi.isSelected()){
           ComboBox_marecredi.setEnabled(true);
        }else{
          ComboBox_marecredi.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_mercrediActionPerformed

    private void CheckBox_jeudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_jeudiActionPerformed
         if(CheckBox_jeudi.isSelected()){
           ComboBox_jeudi.setEnabled(true);
        }else{
          ComboBox_jeudi.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_jeudiActionPerformed

    private void CheckBox_samediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_samediActionPerformed
      
         if(CheckBox_samedi.isSelected()){
           ComboBox_samedi.setEnabled(true);
        }else{
          ComboBox_samedi.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_samediActionPerformed
   boolean G=true;
    private void ComboBox_marecrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_marecrediActionPerformed
   G=true;
//      A=true;
        String jeur="الاربعاء";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_marecredi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
               G=false;
             }
         } catch (Exception e) {
              
         }
         if(!G){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
             if(B && C && D && E && F && H){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
             }
        
         }
        
    }//GEN-LAST:event_ComboBox_marecrediActionPerformed
 boolean B=true;
    private void ComboBox_vendrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_vendrediActionPerformed
        // TODO add your handling code here:
       B=true;
//             A=true;   
           String jeur="الجمعة";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_vendredi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
                 B=false;
//                 A=false;   
             }
         } catch (Exception e) {
              
         }
         if(!B ){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
             if(G && C && D && E && F && H){
                 Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
             }
         
         }
         
        
    }//GEN-LAST:event_ComboBox_vendrediActionPerformed

    private void Button_groupe_scienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_groupe_scienceActionPerformed
     
        
//        if(!A){
        
        /*
        Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_Massage);
        
        }
*/
//        else{
        
         String module= ComboBox_module.getSelectedItem().toString();
          String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
            String nom_groupe=   Txt_nomgroupe.getText();
          
           
 String Query= "INSERT INTO `groupe`(`Nom_Groupe`, `Num_Enseignant`, `Num_Module`, `Nom_Salle`)SELECT ?,E.`Num_Enseignant`,M.`Num_Module`,? FROM `enseignant` E,`module` M WHERE E.`Nom_Enseignant`=? AND M.`Nom_Module`=?"; 

            try {          
                
                
               prepared=  login.cnx.prepareStatement(Query);
                
               prepared.setString(1, nom_groupe);
               prepared.setString(2,Salle );
               prepared.setString(3,enseignant );
               prepared.setString(4,module );
               
                prepared.execute();

                 Txt_nomgroupe.setText("");
             
               
           
            } catch ( Exception e) {
               // JOptionPane.showMessageDialog(null,e+ "NO");
       JOptionPane.showMessageDialog(null,"تمت اضافة هذا الفوج بالفعل","Missing information",JOptionPane.ERROR_MESSAGE);
            }
        
        
        
           if(CheckBox_vendredi.isSelected()){
                String jeur ="الجمعة";
                String heure_debut= ComboBox_vendredi.getSelectedItem().toString();
                String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
                prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }
             
           if(CheckBox_samedi.isSelected()){
               String jeur ="السبت";
               String heure_debut= ComboBox_samedi.getSelectedItem().toString();
               String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }
           
           if(CheckBox_dimanche.isSelected()){
                 String jeur ="الاحد";
                 String heure_debut= ComboBox_dimanche.getSelectedItem().toString();
                 String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }
     
           if(CheckBox_lundi.isSelected()){
               String jeur ="الاثنين";
               String heure_debut= ComboBox_lundi.getSelectedItem().toString();
               String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }

           if(CheckBox_mardi.isSelected()){
               String jeur ="الثلاثاء";
               String heure_debut= ComboBox_maredi.getSelectedItem().toString();
               String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {         
               prepared=  login.cnx.prepareStatement(sql); 
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }

           if(CheckBox_mercredi.isSelected()){
            String jeur ="الاربعاء";
            String heure_debut= ComboBox_marecredi.getSelectedItem().toString();
   String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           
           }
           if(CheckBox_jeudi.isSelected()){
            String jeur ="الخميس";
            String heure_debut= ComboBox_jeudi.getSelectedItem().toString();
   String sql="INSERT INTO `affectation_groupe_sciene`(`jour`, `Heure_debut`, `Num_Groupe`) SELECT ?,?,`Num_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)" ;        
           try {          
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setString(1, jeur);
               prepared.setString(2,heure_debut );
               prepared.execute();
            } catch ( Exception e) {
                JOptionPane.showMessageDialog(null,e+ "NO");
            }
           }
            this.dispose();
//        }   
    }//GEN-LAST:event_Button_groupe_scienceActionPerformed

    private void CheckBox_vendrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_vendrediActionPerformed
        
        if(CheckBox_vendredi.isSelected()){
           ComboBox_vendredi.setEnabled(true);
        }else{
          ComboBox_vendredi.setEnabled(false);
        }
        
    }//GEN-LAST:event_CheckBox_vendrediActionPerformed

    private void CheckBox_dimancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_dimancheActionPerformed
         if(CheckBox_dimanche.isSelected()){
           ComboBox_dimanche.setEnabled(true);
        }else{
          ComboBox_dimanche.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_dimancheActionPerformed

    private void CheckBox_mardiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_mardiActionPerformed
         if(CheckBox_mardi.isSelected()){
           ComboBox_maredi.setEnabled(true);
        }else{
          ComboBox_maredi.setEnabled(false);
        }
    }//GEN-LAST:event_CheckBox_mardiActionPerformed

    private void CheckBox_vendrediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox_vendrediMouseClicked
        // TODO add your handling code here:
         
        
        
    }//GEN-LAST:event_CheckBox_vendrediMouseClicked
    boolean A;
    private void ComboBox_vendrediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_vendrediMouseClicked

    }//GEN-LAST:event_ComboBox_vendrediMouseClicked

    private void ComboBox_samediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_samediMouseClicked

    }//GEN-LAST:event_ComboBox_samediMouseClicked

    private void ComboBox_dimancheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_dimancheMouseClicked
       
    }//GEN-LAST:event_ComboBox_dimancheMouseClicked

    private void ComboBox_lundiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_lundiMouseClicked
    
    }//GEN-LAST:event_ComboBox_lundiMouseClicked

    private void ComboBox_marediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_marediMouseClicked
  
    }//GEN-LAST:event_ComboBox_marediMouseClicked

    private void ComboBox_marecrediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_marecrediMouseClicked

    }//GEN-LAST:event_ComboBox_marecrediMouseClicked

    private void ComboBox_jeudiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBox_jeudiMouseClicked
      
    }//GEN-LAST:event_ComboBox_jeudiMouseClicked
 boolean C=true;
 
    private void ComboBox_samediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_samediActionPerformed
           C=true;
//            A=true;
           String jeur="السبت";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_samedi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
               C=false;
             }
         } catch (Exception e) {
              
         }
           if(!C ){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
               if(G && B && D && E && F && H){
                   Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
               }
         
         }
        
    }//GEN-LAST:event_ComboBox_samediActionPerformed
boolean D=true;
    private void ComboBox_dimancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_dimancheActionPerformed
     D=true;
//     A=true;
           String jeur="الاحد";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_dimanche.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
               D=false;
             }
         } catch (Exception e) {
              
         }
          if(! D ){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
              if(G && B && C && E && F && H){ 
                  Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
              }
        
         }
         
    }//GEN-LAST:event_ComboBox_dimancheActionPerformed
boolean E=true;
    private void ComboBox_lundiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_lundiActionPerformed
        E=true;
//        A=true;
         String jeur="الاثنين";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_lundi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
               E=false;
             }
         } catch (Exception e) {
              
         }
          if(!E ){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add( Panel_Massage);
         
         }
         else{
              if(G && B && C && D && F && H){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
              }
         
         }
    }//GEN-LAST:event_ComboBox_lundiActionPerformed
boolean F=true;
    private void ComboBox_marediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_marediActionPerformed
       F=true;
//       A=true;
          String jeur="الثلاثاء";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_maredi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
               F=false;
             }
         } catch (Exception e) {
              
         }
          if(!F){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
              if(G && B && C && D && E && H){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
              }
         
          }
    }//GEN-LAST:event_ComboBox_marediActionPerformed
boolean H=true;
    private void ComboBox_jeudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_jeudiActionPerformed
         H=true;
//        A=true;
         String jeur="الخميس";
           String enseignant= ComboBox_ensein.getSelectedItem().toString();
           String Salle= ComboBox_Salle.getSelectedItem().toString();
           String Heure_debut= ComboBox_jeudi.getSelectedItem().toString();
           
             String sql="SELECT * FROM `groupe` G,`affectation_groupe_sciene` AGS \n" +
                        "WHERE G.`Num_Groupe`=AGS.`Num_Groupe` \n" +
                        "AND (G.`Num_Enseignant` IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) OR G.`Nom_Salle`=?)\n" +
                        "AND(AGS.`jour`=? AND AGS.`Heure_debut`=?) ";

         try {
             prepared=  login.cnx.prepareStatement(sql);
            prepared.setString(1,enseignant );
               prepared.setString(2,Salle );
               prepared.setString(3, jeur);
               prepared.setString(4, Heure_debut);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
                 H=false;
             }
         } catch (Exception e) {
              
         }  
         if(!H){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(  Panel_Massage);
         
         }
         else{
             if(G && B && C && D && E && F ){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_vide);
             }
        
          }
         
    }//GEN-LAST:event_ComboBox_jeudiActionPerformed
/*
    private void nom_groupe(){
    
    String sql="SELECT `Nom_Groupe` FROM `groupe` WHERE `Num_Groupe`=(SELECT MAX(`Num_Groupe`)FROM `groupe`)";        


         try {
             prepared=  login.cnx.prepareStatement(sql);
            
            
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
         Label_groupe.setText(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
    
    
    }
*/
    
    private void vendredi_Combobox(){
    
    
            
           String jeur="الجمعة";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_vendredi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void samdi_Combobox(){
    
    
            
           String jeur="السبت";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_samedi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void dimanche_Combobox(){
    
    
            
           String jeur="الاحد";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_dimanche.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void lundi_Combobox(){
    
    
            
           String jeur="الاثنين";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_lundi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void maredi_Combobox(){
    
    
            
           String jeur="الثلاثاء";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_maredi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void marecredi_Combobox(){
    
            
           String jeur="الاربعاء";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_marecredi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }
        
    }
     
    private void jeudi_Combobox(){
    

            
           String jeur="الخميس";
             String sql="SELECT `Heure_debut` FROM `sience` WHERE `jour`=?";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, jeur);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_jeudi.addItem(rs.getString(1));
             }
         } catch (Exception e) {
              
         }    
    }
    
    
     private void module_combobox(){
    
    String sql="SELECT * FROM `module` ";

   
        try {
            prepared=  login.cnx.prepareStatement(sql);
            ResultSet rs=  prepared.executeQuery();
          
            while(rs.next()){
            ComboBox_module.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }
    
     private void enseignant_combobox(){
    
    String sql="SELECT * FROM `enseignant` ";

   
        try {
            prepared=  login.cnx.prepareStatement(sql);
            ResultSet rs=  prepared.executeQuery();
          
            while(rs.next()){
            ComboBox_ensein.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }
    
     private void Salle_combobox(){
    
    String sql="SELECT * FROM `salle` ";

   
        try {
            prepared=  login.cnx.prepareStatement(sql);
            ResultSet rs=  prepared.executeQuery();
          
            while(rs.next()){
            ComboBox_Salle.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affectation_groupe_science1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affectation_groupe_science1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affectation_groupe_science1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affectation_groupe_science1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affectation_groupe_science1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_groupe_science;
    private javax.swing.JCheckBox CheckBox_dimanche;
    private javax.swing.JCheckBox CheckBox_jeudi;
    private javax.swing.JCheckBox CheckBox_lundi;
    private javax.swing.JCheckBox CheckBox_mardi;
    private javax.swing.JCheckBox CheckBox_mercredi;
    private javax.swing.JCheckBox CheckBox_samedi;
    private javax.swing.JCheckBox CheckBox_vendredi;
    private javax.swing.JComboBox<String> ComboBox_Salle;
    private javax.swing.JComboBox<String> ComboBox_dimanche;
    private javax.swing.JComboBox<String> ComboBox_ensein;
    private javax.swing.JComboBox<String> ComboBox_jeudi;
    private javax.swing.JComboBox<String> ComboBox_lundi;
    private javax.swing.JComboBox<String> ComboBox_marecredi;
    private javax.swing.JComboBox<String> ComboBox_maredi;
    private javax.swing.JComboBox<String> ComboBox_module;
    private javax.swing.JComboBox<String> ComboBox_samedi;
    private javax.swing.JComboBox<String> ComboBox_vendredi;
    private javax.swing.JPanel Panel_M_P;
    private javax.swing.JPanel Panel_Massage;
    private javax.swing.JPanel Panel_vide;
    private javax.swing.JTextField Txt_nomgroupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
