/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static Main.Main.tabel_étudiants;
import javax.swing.JComboBox;
import school0.pkg1.login;

/**
 *
 * @author MZI System
 */
public class ajouter_reservation extends javax.swing.JFrame {

    /**
     * Creates new form ajouter_reservation
     */
    public ajouter_reservation() {
        initComponents();
        updateCompo();
    }
 PreparedStatement prepared;
    ResultSet result;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nivo = new javax.swing.JComboBox<>();
        ComboBox_module = new javax.swing.JComboBox<>();
        ComboBox_enseignant = new javax.swing.JComboBox<>();
        ComboBox_groupe = new javax.swing.JComboBox<>();
        RZ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nom_etuden1 = new javax.swing.JLabel();
        Panel_M_P = new javax.swing.JPanel();
        Panel_Vide = new javax.swing.JPanel();
        Panel_Massage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("المرحلة :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("المادة :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("الاستاذ :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("الفوج :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("الطالب :");

        nivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        nivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivoActionPerformed(evt);
            }
        });

        ComboBox_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_moduleActionPerformed(evt);
            }
        });

        ComboBox_enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_enseignantActionPerformed(evt);
            }
        });

        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Panel_M_P.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout Panel_VideLayout = new javax.swing.GroupLayout(Panel_Vide);
        Panel_Vide.setLayout(Panel_VideLayout);
        Panel_VideLayout.setHorizontalGroup(
            Panel_VideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Panel_VideLayout.setVerticalGroup(
            Panel_VideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Panel_M_P.add(Panel_Vide, "card2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("اختيار خاطئ");

        javax.swing.GroupLayout Panel_MassageLayout = new javax.swing.GroupLayout(Panel_Massage);
        Panel_Massage.setLayout(Panel_MassageLayout);
        Panel_MassageLayout.setHorizontalGroup(
            Panel_MassageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MassageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_MassageLayout.setVerticalGroup(
            Panel_MassageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_MassageLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Panel_M_P.add(Panel_Massage, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_module, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_enseignant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_groupe, 0, 105, Short.MAX_VALUE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(RZ, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_M_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(nom_etuden1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RZ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBox_module, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBox_enseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Panel_M_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(nom_etuden1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivoActionPerformed
       ComboBox_module.removeAllItems();
             nivo.addActionListener(nivo) ;
            String selectedvalue=(String) nivo.getSelectedItem();
             String sql="SELECT * FROM `module` WHERE `Num_niveau` IN(SELECT `Num_niveau` FROM `niveau` WHERE `Nom_niveau`=?)";

         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, selectedvalue);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_module.addItem(rs.getString(2));
             }
         } catch (Exception e) {
              
         }
    }//GEN-LAST:event_nivoActionPerformed

    private void ComboBox_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_moduleActionPerformed
       ComboBox_enseignant.removeAllItems();
             ComboBox_module.addActionListener(ComboBox_module) ;
            String selectedvalue=(String) ComboBox_module.getSelectedItem();
 String sql="SELECT  * FROM `enseignant` WHERE `Num_Enseignant`IN(SELECT `Num_Enseignant` FROM `groupe` WHERE `groupe`.`Num_Module` IN(SELECT `Num_Module` FROM `module` WHERE `Nom_Module`=?))";
         try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, selectedvalue);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_enseignant.addItem(rs.getString(2));
             }
         } catch (Exception e) {
              
         }
    }//GEN-LAST:event_ComboBox_moduleActionPerformed

    private void ComboBox_enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_enseignantActionPerformed
        
        ComboBox_groupe.removeAllItems();
             ComboBox_enseignant.addActionListener(ComboBox_enseignant) ;
            String selectedvalue=(String) ComboBox_enseignant.getSelectedItem();
            String module= (String)ComboBox_module.getSelectedItem();
    String sql="SELECT DISTINCT `Num_Groupe`,`Nom_Groupe` FROM `groupe` G,`enseignant` WHERE G.`Num_Enseignant`"
              +"IN(SELECT `Num_Enseignant` FROM `enseignant` WHERE `Nom_Enseignant`=?) AND G.`Num_Module`"
              +" IN(SELECT `Num_Module` FROM `module` WHERE `Nom_Module`=? )";
   //  String sql= " SELECT DISTINCT `Nom_Groupe` FROM `groupe` G,`enseignant` E,`module` M WHERE G.`Num_Enseignant`=E.`Num_Enseignant` AND G.`Num_Module`=M.`Num_Module` AND G.`Num_Enseignant`IN(SELECT E.`Num_Enseignant` FROM `enseignant` WHERE E.`Nom_Enseignant`=?) AND G.`Num_Module` IN(SELECT M.`Num_Module` FROM `module` M WHERE M.`Nom_Module`=?)"; 

  try {
             prepared=  login.cnx.prepareStatement(sql);
              prepared.setString(1, selectedvalue);
                prepared.setString(2, module);
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
             ComboBox_groupe.addItem(rs.getString(2));
             }
         } catch (Exception e) {
              
         }
        
    }//GEN-LAST:event_ComboBox_enseignantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
     boolean t=true;   
    t= Massage_De_Control();
         if(!t){
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_Massage);
         }
         else{
             
              Panel_M_P.removeAll();
        Panel_M_P.repaint();
        Panel_M_P.revalidate();
        Panel_M_P.add(Panel_Vide);
         
      //  int index=tabel_étudiants.getSelectedRow();
      int index=Integer.parseInt(RZ.getText());
       String id= tabel_étudiants.getModel().getValueAt(index, 9).toString();
         String groupe= (String)ComboBox_groupe.getSelectedItem().toString();
           int idd=Integer.parseInt(id);
           System.out.println(idd +"");
        
 String sql= "INSERT INTO `reservation`(`Date_Reservation`,`Num_Etudient`, `Num_Groupe`)"
 +"SELECT LOCALTIME(),?,G.`Num_Groupe` FROM `groupe` G WHERE  G.`Nom_Groupe`=?";     
      
   try {
  
               prepared=  login.cnx.prepareStatement(sql);
               prepared.setInt(1, idd);
               prepared.setString(2,groupe );
               prepared.execute();

            } catch ( Exception e) {
               JOptionPane.showMessageDialog(null,e+ "NO");
     //  JOptionPane.showMessageDialog(null,"تمت اضافة هذا الفوج بالفعل","Missing information",JOptionPane.ERROR_MESSAGE);
            }
        this.dispose();
      
         }
         
    }//GEN-LAST:event_jButton1ActionPerformed

     private boolean Massage_De_Control(){
    boolean R=true;
     
           int index = tabel_étudiants.getSelectedRow();
       String id= tabel_étudiants.getModel().getValueAt(index, 9).toString();
           String nom_groupe= ComboBox_groupe.getSelectedItem().toString();
           
             String sql="SELECT G1.`Nom_Groupe`,AGS1.`jour`, AGS1.`Heure_debut` FROM `affectation_groupe_sciene`AGS1,`groupe`G1,`etudient`E, `reservation`R WHERE E.`Num_Etudient`=R.`Num_Etudient` AND G1.`Num_Groupe`=R.`Num_Groupe` AND G1.`Num_Groupe` = AGS1.`Num_Groupe` AND E.`Num_Etudient`=? AND EXISTS( SELECT G.`Nom_Groupe`,AGS.`jour`, AGS.`Heure_debut` FROM `affectation_groupe_sciene`AGS,`groupe`G WHERE G.`Num_Groupe`= AGS.`Num_Groupe` AND G.`Nom_Groupe`=? AND G1.`Num_Groupe`<> G.`Num_Groupe` AND(AGS.`jour`=AGS1.`jour`)AND(AGS.`Heure_debut`= AGS1.`Heure_debut`) )";

         try {
                prepared=  login.cnx.prepareStatement(sql);
                prepared.setString(1,id );
                prepared.setString(2,nom_groupe );
               
             ResultSet rs=  prepared.executeQuery();
             while(rs.next()){
//               A=false;
                 R=false;
             }
         } catch (Exception e) {
              
         }  
    
         return R;
    }
    
    
     private void updateCompo(){
    
    String sql="SELECT * FROM `niveau` ";

   
        try {
            prepared=  login.cnx.prepareStatement(sql);
            ResultSet rs=  prepared.executeQuery();
          
            while(rs.next()){
            nivo.addItem(rs.getString(2));
            }
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouter_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouter_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouter_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouter_reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouter_reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_enseignant;
    private javax.swing.JComboBox<String> ComboBox_groupe;
    private javax.swing.JComboBox<String> ComboBox_module;
    private javax.swing.JPanel Panel_M_P;
    private javax.swing.JPanel Panel_Massage;
    private javax.swing.JPanel Panel_Vide;
    public javax.swing.JLabel RZ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> nivo;
    public javax.swing.JLabel nom_etuden1;
    // End of variables declaration//GEN-END:variables
}
